//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "html_pages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub html: String,
    pub update_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
