//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::html_pages::Entity as HtmlPages;
pub use super::message::Entity as Message;
pub use super::module_config::Entity as ModuleConfig;
pub use super::scene::Entity as Scene;
pub use super::user::Entity as User;
