[package]
name = "nihility"
version = "0.1.0"
edition = "2024"

[features]
chat-bot = ["nihility-input-chat"]
simple-memory = ["nihility-memory-simple"]
api-model = ["nihility-model-api"]

[dependencies]
nihility-common = { workspace = true }
nihility-input-chat = { path = "plugins/nihility-input-chat", optional = true }
nihility-memory-simple = { path = "plugins/nihility-memory-simple", optional = true }
nihility-model-api = { path = "plugins/nihility-model-api", optional = true }

tracing-subscriber = { version = "0.3", features = ["local-time", "ansi", "fmt", "std"] }
tracing-appender = { version = "0.2" }
time = { version = "0.3", default-features = false, features = ["parsing"] }
figment = { version = "0.10", features = ["json", "toml", "yaml"] }
toml = { version = "0.8", default-features = false, features = ["display"] }

tokio = { workspace = true, features = ["macros"] }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

[workspace.dependencies]
nihility-common = { path = "common", version = "0.1.0" }

tokio = { version = "1.44", default-features = false, features = ["sync", "rt", "rt-multi-thread", "tracing"] }
anyhow = { version = "1", default-features = false }
tracing = { version = "0.1" }
uuid = { version = "1.7", default-features = false, features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
lazy_static = { version = "1", default-features = false }
async-trait = { version = "0.1" }

[workspace]
members = ["common", "plugins/*"]
