services:
  nihility:
    image: ghcr.io/nihilityer/nihility:main
    #    build: .
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./chromium:/app/chromium
      - ./model:/app/model
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
