services:
  server:
    image: ghcr.io/nihilityer/nihility:main
    ports:
      - '8080:8080/tcp'
      - '8080:8080/udp'
    volumes:
      - ./config:/app/config
      - ./chromium:/app/chromium
      - ./model:/app/model
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
