//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "msg_type")]
pub enum MsgType {
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "audio")]
    Audio,
    #[sea_orm(string_value = "image")]
    Image,
    #[sea_orm(string_value = "video")]
    Video,
}
